package com.company.orderapproval.customer.service;
import com.company.orderapproval.branch.entity.Branch; import com.company.orderapproval.branch.repository.BranchRepository; import com.company.orderapproval.common.exception.*; import com.company.orderapproval.common.util.SecurityContextHelper; import com.company.orderapproval.customer.dto.*; import com.company.orderapproval.customer.entity.*; import com.company.orderapproval.customer.repository.BusinessCustomerRepository; import com.company.orderapproval.user.entity.User; import com.company.orderapproval.user.repository.UserRepository; import jakarta.servlet.http.HttpServletRequest; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class BusinessCustomerServiceImpl implements BusinessCustomerService { private final BusinessCustomerRepository repo; private final BranchRepository branches; private final UserRepository users; public BusinessCustomerServiceImpl(BusinessCustomerRepository repo,BranchRepository branches,UserRepository users){this.repo=repo;this.branches=branches;this.users=users;}
 public Page<BusinessCustomerResponse> list(UUID organizationId,UUID branchId,String city,BusinessCustomerStatus status,String search,Pageable p){ UUID org=SecurityContextHelper.isSuperAdmin()?organizationId:SecurityContextHelper.getCurrentOrganizationId(); UUID scopedBranch=branchId; if(!SecurityContextHelper.isSuperAdmin()){ UUID currentBranch=users.findById(SecurityContextHelper.getCurrentUserId()).map(User::getBranchId).orElse(null); if(currentBranch!=null) scopedBranch=currentBranch; UUID customerId=users.findById(SecurityContextHelper.getCurrentUserId()).map(User::getBusinessCustomerId).orElse(null); if(customerId!=null){return repo.findById(customerId).filter(c->(search==null||search.isBlank()||c.getName().toLowerCase().contains(search.toLowerCase()))).map(c->new PageImpl<BusinessCustomer>(List.of(c),p,1)).orElse(new PageImpl<BusinessCustomer>(List.of(),p,0)).map(this::response);} } return repo.search(org,scopedBranch,status,city,search,p).map(this::response); }
 public BusinessCustomerResponse get(UUID id){BusinessCustomer c=access(id);enforceBranchScope(branch(c.getBranchId()));return response(c);}
 @Transactional public BusinessCustomerResponse create(UUID branchId,CreateBusinessCustomerRequest r,HttpServletRequest h){Branch b=branch(branchId);enforceBranchScope(b);String code=r.customerCode().trim().toUpperCase(Locale.ROOT);if(repo.findByBranchIdAndCustomerCode(branchId,code).isPresent())throw new ConflictException("Customer code already exists in branch");BusinessCustomer c=new BusinessCustomer();c.setOrganizationId(b.getOrganizationId());c.setBranchId(branchId);c.setCustomerCode(code);c.setName(r.name().trim());c.setCity(r.city());c.setState(r.state());c.setAddress(r.address());c.setPincode(r.pincode());c.setEmail(r.email());c.setPhone(r.phone());c.setCreatedBy(SecurityContextHelper.getCurrentUserId());c.setUpdatedBy(SecurityContextHelper.getCurrentUserId());repo.save(c);return response(c);}
 @Transactional public BusinessCustomerResponse update(UUID id,UpdateBusinessCustomerRequest r,HttpServletRequest h){BusinessCustomer c=access(id);enforceBranchScope(branch(c.getBranchId()));c.setName(r.name().trim());c.setCity(r.city());c.setState(r.state());c.setAddress(r.address());c.setPincode(r.pincode());c.setEmail(r.email());c.setPhone(r.phone());c.setStatus(r.status());c.setUpdatedBy(SecurityContextHelper.getCurrentUserId());repo.save(c);return response(c);}
 private Branch branch(UUID id){Branch b=branches.findById(id).orElseThrow(()->new ResourceNotFoundException("Branch not found"));if(!SecurityContextHelper.isSuperAdmin()&&!b.getOrganizationId().equals(SecurityContextHelper.getCurrentOrganizationId()))throw new ForbiddenException("Cannot access another organization");return b;}
 private void enforceBranchScope(Branch b){ if(!SecurityContextHelper.isSuperAdmin()){ UUID currentBranch=users.findById(SecurityContextHelper.getCurrentUserId()).map(User::getBranchId).orElse(null); if(currentBranch != null && !currentBranch.equals(b.getId())) throw new ForbiddenException("Cannot access another branch"); } }
 private BusinessCustomer access(UUID id){BusinessCustomer c=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Business customer not found"));if(!SecurityContextHelper.isSuperAdmin()&&!c.getOrganizationId().equals(SecurityContextHelper.getCurrentOrganizationId()))throw new ForbiddenException("Cannot access another organization");UUID currentCustomer=users.findById(SecurityContextHelper.getCurrentUserId()).map(User::getBusinessCustomerId).orElse(null);if(currentCustomer!=null&&!currentCustomer.equals(id))throw new ForbiddenException("Cannot access another business customer");return c;}
 private BusinessCustomerResponse response(BusinessCustomer c){return new BusinessCustomerResponse(c.getId(),c.getOrganizationId(),c.getBranchId(),c.getCustomerCode(),c.getName(),c.getCity(),c.getState(),c.getAddress(),c.getPincode(),c.getEmail(),c.getPhone(),c.getStatus(),c.getCreatedAt(),c.getUpdatedAt());}
}
