package com.company.orderapproval.customer.location.service;
import com.company.orderapproval.common.exception.*; import com.company.orderapproval.common.util.SecurityContextHelper; import com.company.orderapproval.customer.entity.BusinessCustomer; import com.company.orderapproval.customer.repository.BusinessCustomerRepository; import com.company.orderapproval.customer.location.dto.*; import com.company.orderapproval.customer.location.entity.*; import com.company.orderapproval.customer.location.repository.BusinessCustomerLocationRepository; import com.company.orderapproval.user.entity.User; import com.company.orderapproval.user.repository.UserRepository; import jakarta.servlet.http.HttpServletRequest; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class BusinessCustomerLocationServiceImpl implements BusinessCustomerLocationService { private final BusinessCustomerLocationRepository repo; private final BusinessCustomerRepository customers; private final UserRepository users; public BusinessCustomerLocationServiceImpl(BusinessCustomerLocationRepository repo,BusinessCustomerRepository customers,UserRepository users){this.repo=repo;this.customers=customers;this.users=users;}
 public Page<BusinessCustomerLocationResponse> list(UUID customerId,String search,BusinessCustomerLocationStatus status,Pageable p){BusinessCustomer c=customer(customerId);scope(c);UUID currentLocation=SecurityContextHelper.isSuperAdmin()?null:users.findById(SecurityContextHelper.getCurrentUserId()).map(User::getBusinessCustomerLocationId).orElse(null);if(currentLocation!=null){return repo.findById(currentLocation).filter(l->l.getBusinessCustomerId().equals(customerId)).map(l->new PageImpl<BusinessCustomerLocation>(List.of(l),p,1)).orElse(new PageImpl<BusinessCustomerLocation>(List.of(),p,0)).map(this::response);}return repo.search(customerId,search,status,p).map(this::response);}
 public BusinessCustomerLocationResponse get(UUID id){BusinessCustomerLocation l=access(id);return response(l);}
 @Transactional public BusinessCustomerLocationResponse create(UUID customerId,CreateBusinessCustomerLocationRequest r,HttpServletRequest h){BusinessCustomer c=customer(customerId);scope(c);String code=r.locationCode().trim().toUpperCase(Locale.ROOT);if(repo.findByBusinessCustomerIdAndLocationCode(customerId,code).isPresent())throw new ConflictException("Location code already exists for this customer");BusinessCustomerLocation l=new BusinessCustomerLocation();l.setBusinessCustomerId(c.getId());l.setOrganizationId(c.getOrganizationId());l.setBranchId(c.getBranchId());l.setLocationCode(code);l.setLocationName(r.locationName().trim());l.setCity(r.city().trim());l.setState(r.state());l.setAddress(r.address());l.setPincode(r.pincode());repo.save(l);return response(l);}
 @Transactional public BusinessCustomerLocationResponse update(UUID id,UpdateBusinessCustomerLocationRequest r,HttpServletRequest h){BusinessCustomerLocation l=access(id);l.setLocationName(r.locationName().trim());l.setCity(r.city().trim());l.setState(r.state());l.setAddress(r.address());l.setPincode(r.pincode());l.setStatus(r.status());repo.save(l);return response(l);}
 private BusinessCustomer customer(UUID id){return customers.findById(id).orElseThrow(()->new ResourceNotFoundException("Business customer not found"));}
 private void scope(BusinessCustomer c){if(SecurityContextHelper.isSuperAdmin())return; if(!c.getOrganizationId().equals(SecurityContextHelper.getCurrentOrganizationId()))throw new ForbiddenException("Cannot access another organization");User u=users.findById(SecurityContextHelper.getCurrentUserId()).orElseThrow(()->new ResourceNotFoundException("User not found"));if(u.getBranchId()!=null&&!u.getBranchId().equals(c.getBranchId()))throw new ForbiddenException("Cannot access another branch");if(u.getBusinessCustomerId()!=null&&!u.getBusinessCustomerId().equals(c.getId()))throw new ForbiddenException("Cannot access another business customer");}
 private BusinessCustomerLocation access(UUID id){BusinessCustomerLocation l=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Business customer location not found"));BusinessCustomer c=customer(l.getBusinessCustomerId());scope(c);if(!SecurityContextHelper.isSuperAdmin()){UUID currentLocation=users.findById(SecurityContextHelper.getCurrentUserId()).map(User::getBusinessCustomerLocationId).orElse(null);if(currentLocation!=null&&!currentLocation.equals(id))throw new ForbiddenException("Cannot access another business customer location");}return l;}
 private BusinessCustomerLocationResponse response(BusinessCustomerLocation l){return new BusinessCustomerLocationResponse(l.getId(),l.getBusinessCustomerId(),l.getOrganizationId(),l.getBranchId(),l.getLocationCode(),l.getLocationName(),l.getCity(),l.getState(),l.getAddress(),l.getPincode(),l.getStatus(),l.getCreatedAt(),l.getUpdatedAt());}
}
