ALTER TABLE roles ADD COLUMN level INTEGER;
ALTER TABLE permissions ADD COLUMN delegation_level INTEGER;

UPDATE roles
SET level = CASE name
    WHEN 'SUPER_ADMIN' THEN 100
    WHEN 'ORGANIZATION_ADMIN' THEN 80
    WHEN 'BRANCH_ADMIN' THEN 60
    WHEN 'INVENTORY_MANAGER' THEN 50
    WHEN 'CUSTOMER_ADMIN' THEN 40
    WHEN 'EMPLOYEE' THEN 30
    WHEN 'FINAL_APPROVER' THEN 30
    WHEN 'MID_APPROVER' THEN 20
    WHEN 'ORDER_REVIEWER' THEN 20
    WHEN 'ORDER_APPROVER' THEN 20
    WHEN 'ORDER_CREATOR' THEN 10
    WHEN 'CUSTOMER' THEN 5
    WHEN 'CUSTOMER_USER' THEN 5
    ELSE 10
END;

UPDATE permissions
SET delegation_level = CASE
    WHEN module = 'ORGANIZATION' THEN 100
    WHEN module = 'AUDIT' THEN 80
    WHEN module = 'BRANCH' THEN 80
    WHEN code IN ('ROLE_CREATE', 'ROLE_UPDATE') THEN 80
    WHEN code IN ('USER_DISABLE') THEN 60
    WHEN module IN ('INVENTORY', 'STOCK_REQUEST') THEN 50
    WHEN module IN ('CUSTOMER', 'PRODUCT') THEN 40
    WHEN code IN ('USER_VIEW', 'USER_CREATE', 'USER_UPDATE') THEN 40
    WHEN code IN ('ROLE_VIEW', 'ROLE_ASSIGN') THEN 40
    WHEN code IN ('ORDER_REVIEW', 'ORDER_APPROVE', 'ORDER_REJECT') THEN 20
    WHEN module = 'ORDER' THEN 10
    ELSE 100
END;

ALTER TABLE roles ALTER COLUMN level SET NOT NULL;
ALTER TABLE permissions ALTER COLUMN delegation_level SET NOT NULL;

ALTER TABLE roles ALTER COLUMN level SET DEFAULT 10;
ALTER TABLE permissions ALTER COLUMN delegation_level SET DEFAULT 100;

CREATE INDEX idx_roles_level ON roles(level);
CREATE INDEX idx_permissions_delegation_level ON permissions(delegation_level);
