INSERT INTO permissions (code, name, description, module) VALUES
('USER_VIEW', 'View users', 'View users in the accessible organization scope', 'USER'),
('USER_CREATE', 'Create users', 'Create users in the accessible organization scope', 'USER'),
('USER_UPDATE', 'Update users', 'Update users in the accessible organization scope', 'USER'),
('USER_DISABLE', 'Disable users', 'Disable or lock users', 'USER'),
('ROLE_VIEW', 'View roles', 'View roles and role assignments', 'ROLE'),
('ROLE_CREATE', 'Create roles', 'Create organization roles', 'ROLE'),
('ROLE_UPDATE', 'Update roles', 'Update role metadata and permissions', 'ROLE'),
('ROLE_ASSIGN', 'Assign roles', 'Assign roles to users', 'ROLE'),
('ORGANIZATION_VIEW', 'View organizations', 'View organizations', 'ORGANIZATION'),
('ORGANIZATION_CREATE', 'Create organizations', 'Create customer or supplier organizations', 'ORGANIZATION'),
('ORGANIZATION_UPDATE', 'Update organizations', 'Update organization data or status', 'ORGANIZATION'),
('PRODUCT_VIEW', 'View products', 'View product catalog records', 'PRODUCT'),
('PRODUCT_CREATE', 'Create products', 'Create product catalog records', 'PRODUCT'),
('PRODUCT_UPDATE', 'Update products', 'Update product catalog records', 'PRODUCT'),
('PRODUCT_DELETE', 'Delete products', 'Delete or retire product catalog records', 'PRODUCT'),
('ORDER_VIEW', 'View orders', 'View orders', 'ORDER'),
('ORDER_CREATE', 'Create orders', 'Create orders', 'ORDER'),
('ORDER_UPDATE', 'Update orders', 'Update orders', 'ORDER'),
('ORDER_SUBMIT', 'Submit orders', 'Submit orders for approval', 'ORDER'),
('ORDER_REVIEW', 'Review orders', 'Review submitted orders', 'ORDER'),
('ORDER_APPROVE', 'Approve orders', 'Approve orders', 'ORDER'),
('ORDER_REJECT', 'Reject orders', 'Reject orders', 'ORDER'),
('INVENTORY_VIEW', 'View inventory', 'View inventory balances', 'INVENTORY'),
('INVENTORY_UPDATE', 'Update inventory', 'Update inventory balances', 'INVENTORY'),
('STOCK_REQUEST_VIEW', 'View stock requests', 'View stock transfer or replenish requests', 'STOCK_REQUEST'),
('STOCK_REQUEST_CREATE', 'Create stock requests', 'Create stock transfer or replenish requests', 'STOCK_REQUEST'),
('STOCK_REQUEST_APPROVE', 'Approve stock requests', 'Approve stock transfer or replenish requests', 'STOCK_REQUEST'),
('AUDIT_VIEW', 'View audit logs', 'View audit log entries', 'AUDIT')
ON CONFLICT (code) DO NOTHING;
